/// Azerbaijani strings — the source of truth for the key set.
/// Every other locale map must contain exactly these keys (enforced by
/// `test/localization_test.dart`).
const Map<String, String> kStringsAz = {
  // ---------------------------------------------------------------- general
  'appName': 'Yol Yoldaşı',
  'appTagline': 'Şəhərlərarası yolu birlikdə gedək',
  'ok': 'Oldu',
  'cancel': 'Ləğv et',
  'save': 'Yadda saxla',
  'delete': 'Sil',
  'edit': 'Redaktə et',
  'retry': 'Yenidən cəhd et',
  'next': 'Növbəti',
  'back': 'Geri',
  'skip': 'Keç',
  'done': 'Hazırdır',
  'close': 'Bağla',
  'search': 'Axtar',
  'confirm': 'Təsdiqlə',
  'reject': 'Rədd et',
  'yes': 'Bəli',
  'no': 'Xeyr',
  'loading': 'Yüklənir…',
  'seeAll': 'Hamısına bax',
  'clear': 'Təmizlə',
  'apply': 'Tətbiq et',
  'reset': 'Sıfırla',
  'optional': 'istəyə bağlı',
  'continueLabel': 'Davam et',
  'share': 'Paylaş',
  'copy': 'Kopyala',
  'copied': 'Kopyalandı',
  'today': 'Bu gün',
  'tomorrow': 'Sabah',
  'yesterday': 'Dünən',
  'from': 'Haradan',
  'to': 'Hara',
  'currency': 'AZN',
  'perSeat': 'yer üçün',
  'rating': 'Reytinq',
  'noResultsTitle': 'Nəticə tapılmadı',
  'noResultsBody': 'Axtarış şərtlərini dəyişib yenidən yoxlayın.',
  'emptyTitle': 'Hələ heç nə yoxdur',
  'refresh': 'Yenilə',
  'showMore': 'Daha çox',
  'showLess': 'Daha az',
  'anonymous': 'Anonim',
  'you': 'Siz',
  'now': 'indi',
  'unknown': 'Naməlum',

  // ------------------------------------------------------------ onboarding
  'onboard1Title': 'Yol yoldaşını tap',
  'onboard1Body':
      'Bakıdan Gəncəyə, Şəkidən Lənkərana — eyni istiqamətə gedən sürücü və sərnişinləri bir araya gətiririk.',
  'onboard2Title': 'Xərci bölüş',
  'onboard2Body':
      'Boş yerlərini elan et, yanacaq xərcini paylaş. Sərnişin üçün taksi qiymətinin bir hissəsinə səfər.',
  'onboard3Title': 'Təhlükəsiz və şəffaf',
  'onboard3Body':
      'Sürücü sənədləri yoxlanılır, hər səfərdən sonra qarşılıqlı reytinq verilir. Nömrə yalnız bron təsdiqlənəndən sonra açılır.',
  'getStarted': 'Başlayaq',

  // ------------------------------------------------------------------ auth
  'loginTitle': 'Xoş gəlmisiniz',
  'loginSubtitle': 'Nömrənizi daxil edin, SMS ilə təsdiq kodu göndərəcəyik.',
  'phoneNumber': 'Telefon nömrəsi',
  'phoneHint': '50 123 45 67',
  'sendCode': 'Kod göndər',
  'termsPrefix': 'Davam etməklə ',
  'termsOfUse': 'İstifadə şərtləri',
  'termsAnd': ' və ',
  'privacyPolicy': 'Məxfilik siyasəti',
  'termsSuffix': ' ilə razılaşırsınız.',
  'otpTitle': 'Kodu daxil edin',
  'changeNumber': 'Nömrəni dəyiş',
  'resendCode': 'Kodu yenidən göndər',
  'resendIn': 'Yenidən göndər',
  'verify': 'Təsdiqlə',
  'otpAutoHint': 'Kod avtomatik oxunacaq',
  'signingIn': 'Giriş edilir…',

  // ------------------------------------------------------------------ role
  'roleTitle': 'Necə istifadə edəcəksiniz?',
  'roleSubtitle': 'Sonra istənilən vaxt dəyişə bilərsiniz.',
  'driver': 'Sürücü',
  'passenger': 'Sərnişin',
  'driverRoleDesc': 'Marşrut elan edirəm, boş yerlərimi paylaşıram.',
  'passengerRoleDesc': 'Səfər axtarıram və yer bron edirəm.',
  'driverMode': 'Sürücü rejimi',
  'passengerMode': 'Sərnişin rejimi',
  'activeMode': 'Rejim',

  // --------------------------------------------------------------- profile
  'profile': 'Profil',
  'profileSetupTitle': 'Özünüzü tanıdın',
  'profileSetupSubtitle': 'Ad və şəkil yol yoldaşlarınızda etibar yaradır.',
  'fullName': 'Ad və soyad',
  'fullNameHint': 'Məsələn: Rəşad Əliyev',
  'about': 'Haqqında',
  'aboutHint': 'Özünüz haqqında bir neçə söz…',
  'gender': 'Cins',
  'male': 'Kişi',
  'female': 'Qadın',
  'genderUnspecified': 'Bildirmək istəmirəm',
  'photo': 'Şəkil',
  'addPhoto': 'Şəkil əlavə et',
  'changePhoto': 'Şəkli dəyiş',
  'removePhoto': 'Şəkli sil',
  'takePhoto': 'Kamera ilə çək',
  'pickFromGallery': 'Qalereyadan seç',
  'editProfile': 'Profili redaktə et',
  'memberSince': 'Qeydiyyat',
  'completedTrips': 'Tamamlanmış səfər',
  'profileSaved': 'Profil yeniləndi',
  'verifiedBadge': 'Təsdiqlənmiş',
  'phoneVerified': 'Nömrə təsdiqlənib',

  // --------------------------------------------------------------- vehicle
  'vehicle': 'Avtomobil',
  'vehicleInfo': 'Avtomobil məlumatları',
  'vehicleBrand': 'Marka',
  'vehicleBrandHint': 'Məsələn: Mercedes-Benz',
  'vehicleModel': 'Model',
  'vehicleModelHint': 'Məsələn: E 200',
  'vehicleColor': 'Rəng',
  'vehiclePlate': 'Dövlət nömrəsi',
  'vehiclePlateHint': '10-AA-123',
  'vehicleYear': 'Buraxılış ili',
  'vehicleSeats': 'Sərnişin yeri',
  'saveVehicle': 'Avtomobili yadda saxla',
  'vehicleSaved': 'Avtomobil məlumatları yadda saxlanıldı',
  'noVehicle': 'Avtomobil əlavə edilməyib',

  // ------------------------------------------------------------- documents
  'documents': 'Sənədlər',
  'documentsTitle': 'Sürücü sənədləri',
  'documentsSubtitle':
      'Elan yerləşdirmək üçün sənədləriniz yoxlanılmalıdır. Yoxlama adətən 24 saat çəkir.',
  'docIdCard': 'Şəxsiyyət vəsiqəsi',
  'docDriverLicense': 'Sürücülük vəsiqəsi',
  'docVehicleRegistration': 'FŞH (qeydiyyat şəhadətnaməsi)',
  'docInsurance': 'İcbari sığorta',
  'docIdCardDesc': 'Ön və arxa tərəf aydın görünsün.',
  'docDriverLicenseDesc': 'Etibarlılıq müddəti bitməmiş olmalıdır.',
  'docVehicleRegistrationDesc': 'Avtomobilin qeydiyyat şəhadətnaməsi.',
  'docInsuranceDesc': 'İcbari sığorta şəhadətnaməsi.',
  'uploadDocument': 'Sənəd yüklə',
  'replaceDocument': 'Sənədi dəyiş',
  'docStatusNotUploaded': 'Yüklənməyib',
  'docStatusPending': 'Yoxlanılır',
  'docStatusApproved': 'Təsdiqləndi',
  'docStatusRejected': 'Rədd edildi',
  'verificationPending': 'Sənədləriniz yoxlanılır',
  'verificationPendingBody':
      'Yoxlama tamamlanana qədər elan yerləşdirə bilməzsiniz.',
  'verificationApproved': 'Sürücü statusunuz təsdiqləndi',
  'verificationRejected': 'Sənədlər rədd edildi',
  'verificationRejectedBody': 'Səbəbi oxuyub sənədləri yenidən yükləyin.',
  'rejectionReason': 'Rədd səbəbi',
  'submitForReview': 'Yoxlamaya göndər',
  'documentsSubmitted': 'Sənədlər yoxlamaya göndərildi',
  'allDocumentsRequired': 'Bütün sənədləri yükləyin',

  // ------------------------------------------------------------------ ride
  'publishRide': 'Elan yerləşdir',
  'publishRideShort': 'Elan ver',
  'editRide': 'Elanı redaktə et',
  'routeStep': 'Marşrut',
  'scheduleStep': 'Tarix və saat',
  'detailsStep': 'Şərtlər',
  'fromCity': 'Haradan',
  'toCity': 'Hara',
  'selectCity': 'Şəhər seçin',
  'searchCity': 'Şəhər axtar',
  'swapCities': 'Yerini dəyiş',
  'date': 'Tarix',
  'time': 'Saat',
  'selectDate': 'Tarix seçin',
  'selectTime': 'Saat seçin',
  'seatsAvailable': 'Boş yer sayı',
  'pricePerSeat': 'Adam başı qiymət',
  'priceHint': 'Məsələn: 15',
  'rideNote': 'Əlavə qeyd',
  'rideNoteHint': 'Dayanacaq nöqtəsi, baqaj şərtləri, siqaret və s.',
  'pickupPoint': 'Görüş nöqtəsi',
  'pickupPointHint': 'Məsələn: 20 Yanvar metrosu',
  'dropoffPoint': 'Düşmə nöqtəsi',
  'publish': 'Elanı yerləşdir',
  'ridePublished': 'Elanınız yayımlandı',
  'rideUpdated': 'Elan yeniləndi',
  'rideDeleted': 'Elan silindi',
  'deleteRideConfirm': 'Elanı silmək istədiyinizə əminsiniz?',
  'deleteRideWithBookings':
      'Bu elanda təsdiqlənmiş bronlar var. Silmə əvəzinə sərnişinlərlə əlaqə saxlayın.',
  'myRides': 'Elanlarım',
  'activeRides': 'Aktiv',
  'pastRides': 'Keçmiş',
  'rideActive': 'Aktiv',
  'rideInactive': 'Deaktiv',
  'rideCompleted': 'Tamamlanıb',
  'rideCancelled': 'Ləğv edilib',
  'activateRide': 'Aktivləşdir',
  'deactivateRide': 'Deaktiv et',
  'rideDetails': 'Səfər haqqında',
  'noRidesYet': 'Hələ elanınız yoxdur',
  'noRidesYetBody': 'İlk marşrutunuzu elan edin və boş yerlərinizi paylaşın.',
  'rideFull': 'Yer qalmayıb',
  'departure': 'Yola düşmə',
  'instantBooking': 'Ani bron',
  'instantBookingDesc': 'Bronlar avtomatik təsdiqlənir',
  'requestBooking': 'Təsdiqli bron',
  'requestBookingDesc': 'Hər bronu özünüz təsdiqləyirsiniz',

  // ---------------------------------------------------------------- search
  'searchTitle': 'Hara gedirsiniz?',
  'searchRides': 'Səfər axtar',
  'anyDate': 'İstənilən tarix',
  'passengersCount': 'Sərnişin sayı',
  'searchResults': 'Axtarış nəticələri',
  'filters': 'Filtrlər',
  'sortBy': 'Sıralama',
  'sortEarliest': 'Ən erkən',
  'sortCheapest': 'Ən ucuz',
  'sortTopRated': 'Ən yüksək reytinq',
  'priceRange': 'Qiymət aralığı',
  'timeOfDay': 'Günün vaxtı',
  'morning': 'Səhər',
  'afternoon': 'Günorta',
  'evening': 'Axşam',
  'night': 'Gecə',
  'onlyVerified': 'Yalnız təsdiqlənmiş sürücülər',
  'noRidesFound': 'Bu marşrutda səfər tapılmadı',
  'noRidesFoundBody':
      'Tarixi dəyişin, yaxud bu marşrut üçün tələb elanı yaradın — sürücülərə çatdıraq.',
  'popularRoutes': 'Populyar marşrutlar',
  'allActiveRides': 'Bütün aktiv elanlar',
  'noActiveRides': 'Hazırda aktiv elan yoxdur',
  'noActiveRidesBody': 'Yeni elanlar dərhal burada görünəcək.',

  // --------------------------------------------------------------- booking
  'bookSeat': 'Yer bron et',
  'bookingTitle': 'Bron',
  'howManySeats': 'Neçə yer lazımdır?',
  'totalPrice': 'Ümumi məbləğ',
  'messageToDriver': 'Sürücüyə mesaj',
  'messageToDriverHint': 'Salam, harada görüşək?',
  'sendRequest': 'Sorğu göndər',
  'bookNow': 'İndi bron et',
  'bookingSent': 'Bron sorğusu göndərildi',
  'bookingConfirmedToast': 'Bron təsdiqləndi',
  'myBookings': 'Rezervasiyalarım',
  'bookingRequests': 'Bron sorğuları',
  'upcoming': 'Qarşıdan gələn',
  'history': 'Tarixçə',
  'statusPending': 'Gözləyir',
  'statusConfirmed': 'Təsdiqləndi',
  'statusRejected': 'Rədd edildi',
  'statusCancelledByPassenger': 'Sərnişin ləğv etdi',
  'statusCancelledByDriver': 'Sürücü ləğv etdi',
  'statusCompleted': 'Tamamlandı',
  'cancelBooking': 'Ləğv et',
  'cancelBookingConfirm': 'Bronu ləğv etmək istədiyinizə əminsiniz?',
  'bookingCancelled': 'Bron ləğv edildi',
  'keepBooking': 'Bronu saxla',
  'cancelReleasesSeat':
      'Yeriniz dərhal boşalır. Fikrinizi dəyişsəniz yenidən bron edə bilərsiniz, amma o vaxta yer başqasına getmiş ola bilər.',
  'rebookSameRide': 'Yenidən bron et',
  'rebookSameRideBody':
      'Bu səfəri ləğv etmisiniz. Yer hələ varsa, yenidən bron edə bilərsiniz.',
  'rideClosedToYou': 'Bu səfər sizin üçün bağlıdır',
  'rideClosedToYouBody':
      'Sürücü qərarını verib, ona görə bu səfərə təkrar müraciət etmək olmaz. Eyni istiqamətdə başqa səfərlərə baxa bilərsiniz.',
  'seatTakenAlready': 'Yer artıq tutulub',
  'seatTakenAlreadyBody':
      'Siz ləğv edəndən sonra yer başqasına gedib. Eyni istiqamətdə başqa səfərlərə baxa bilərsiniz.',
  'blockPassenger': 'Səfəri bu sərnişinə bağla',
  'blockPassengerConfirm':
      'Bu sərnişin həmin səfəri bir daha bron edə bilməyəcək. İstədiyiniz vaxt geri aça bilərsiniz.',
  'passengerBlocked': 'Səfər bu sərnişinə bağlıdır',
  'passengerBlockedBody':
      'Ləğvdən sonra siz bu səfəri ona bağlamısınız — təkrar bron edə bilməz.',
  'unblockPassenger': 'Yenidən aç',
  'passengerBlockedMsg': 'Səfər bu sərnişinə bağlandı',
  'passengerUnblockedMsg': 'Səfər bu sərnişinə yenidən açıldı',
  'lateCancellationWarning':
      'Yola düşməyə az qalıb — indi ləğv etmək qarşı tərəfi çətin vəziyyətdə qoyur.',
  'cancelReasonQuestion': 'Niyə ləğv edirsiniz?',
  'cancelReasonPlanChanged': 'Planım dəyişdi',
  'cancelReasonFoundCheaper': 'Daha sərfəli səfər tapdım',
  'cancelReasonNoAnswer': 'Sürücü cavab vermir',
  'cancelReasonVehicleProblem': 'Avtomobillə problem yarandı',
  'cancelReasonRescheduled': 'Səfərin vaxtını dəyişdim',
  'cancelReasonOther': 'Başqa səbəb',
  'cancelReasonHint': 'Qısaca yazın (istəyə bağlı)',
  'cancellationReasonTitle': 'Ləğv səbəbi',
  'findAnotherRide': 'Başqa səfər tap',
  'findAnotherRideBody':
      'Bu səfərə təkrar müraciət etmək olmaz, amma eyni istiqamətdə ən ucuz səfərlərə baxa bilərsiniz.',
  'confirmBooking': 'Təsdiqlə',
  'rejectBooking': 'Rədd et',
  'bookingConfirmedMsg': 'Bron təsdiqləndi, sərnişinə bildiriş göndərildi.',
  'bookingRejectedMsg': 'Bron rədd edildi.',
  'noBookingsYet': 'Hələ bronunuz yoxdur',
  'noBookingsYetBody': 'Səfər axtarın və ilk yerinizi bron edin.',
  'noRequestsYet': 'Hələ sorğu yoxdur',
  'noRequestsYetBody': 'Elanınıza sorğu gələndə burada görünəcək.',
  'seatsBooked': 'Bron edilmiş yer',
  'bookedBy': 'Bron edən',
  'markCompleted': 'Səfəri tamamla',
  'tripCompleted': 'Səfər tamamlandı',

  // --------------------------------------------------------------- contact
  'contact': 'Əlaqə',
  'callDriver': 'Sürücüyə zəng et',
  'callPassenger': 'Sərnişinə zəng et',
  'sendMessage': 'Mesaj yaz',
  'phoneHiddenTitle': 'Nömrə gizlidir',
  'phoneHiddenBody':
      'Təhlükəsizlik üçün telefon nömrəsi yalnız bron təsdiqlənəndən sonra açılır.',
  'openWhatsapp': 'WhatsApp-da yaz',
  'cannotCall': 'Zəng başladıla bilmədi',

  // ------------------------------------------------------------------ chat
  'chat': 'Söhbət',
  'messages': 'Mesajlar',
  'typeMessage': 'Mesaj yazın…',
  'noMessages': 'Hələ mesaj yoxdur',
  'noMessagesBody': 'Səfərlə bağlı detalları burada dəqiqləşdirin.',
  'noConversations': 'Söhbət yoxdur',
  'noConversationsBody': 'Bron təsdiqlənəndən sonra söhbət açılır.',
  'chatLockedTitle': 'Söhbət bağlıdır',
  'chatLockedBody': 'Bron təsdiqlənəndən sonra yaza bilərsiniz.',

  // --------------------------------------------------------- notifications
  'notifications': 'Bildirişlər',
  'markAllRead': 'Hamısını oxunmuş et',
  'noNotifications': 'Bildiriş yoxdur',
  'noNotificationsBody': 'Bron və səfər yenilikləri burada görünəcək.',
  'notifNewBookingTitle': 'Yeni bron sorğusu',
  'notifInstantBookingTitle': 'Səfərinizə yer bron edildi',
  'notifBookingConfirmedTitle': 'Bronunuz təsdiqləndi',
  'notifBookingRejectedTitle': 'Bronunuz rədd edildi',
  'notifBookingCancelledTitle': 'Bron ləğv edildi',
  'notifRideReminderTitle': 'Səfər xatırlatması',
  'notifRideCancelledTitle': 'Səfər ləğv edildi',
  'notifNewMessageTitle': 'Yeni mesaj',
  'notifReviewRequestTitle': 'Səfəri qiymətləndirin',
  'notifDocsApprovedTitle': 'Sənədləriniz təsdiqləndi',
  'notifDocsRejectedTitle': 'Sənədləriniz rədd edildi',
  'notifDocsApprovedBody': 'İndi elan yerləşdirə bilərsiniz.',
  'notifReason': 'Səbəb',
  'notifAdminMessageTitle': 'Xidmət bildirişi',
  'notifAdminMarketingTitle': 'Kampaniya',
  'notifUnknownTitle': 'Yeni bildiriş',

  // Android bildiriş kanalları — sistem parametrlərində bu adlarla görünür.
  'channelMessages': 'Mesajlar',
  'channelMessagesDesc': 'Söhbətlərdə yeni mesajlar',
  'channelBookings': 'Bronlar',
  'channelBookingsDesc': 'Bron sorğuları, təsdiqlər və ləğvlər',
  'channelReminders': 'Səfər xatırlatmaları',
  'channelRemindersDesc': 'Yola düşməzdən əvvəl xatırlatma',
  'channelMarketing': 'Kampaniyalar',
  'channelMarketingDesc': 'Endirimlər və yeniliklər',
  'channelGeneral': 'Ümumi',
  'channelGeneralDesc': 'Hesab bildirişləri və digərləri',

  // --------------------------------------------------------------- reviews
  'reviews': 'Rəylər',
  'rateTrip': 'Səfəri qiymətləndirin',
  'rateTripSubtitle': 'Rəyiniz digər istifadəçilərə kömək edir.',
  'yourRating': 'Qiymətiniz',
  'writeComment': 'Şərh yazın',
  'writeCommentHint': 'Səfər necə keçdi?',
  'submitReview': 'Rəyi göndər',
  'reviewSubmitted': 'Rəyiniz üçün təşəkkür edirik',
  'noReviews': 'Hələ rəy yoxdur',
  'noReviewsBody': 'İlk rəyi siz yazın.',
  'ratingPoor': 'Pis',
  'ratingFair': 'Orta',
  'ratingGood': 'Yaxşı',
  'ratingVeryGood': 'Çox yaxşı',
  'ratingExcellent': 'Əla',
  'reviewsAsDriver': 'Sürücü kimi',
  'reviewsAsPassenger': 'Sərnişin kimi',
  'pendingReviews': 'Qiymətləndirilməmiş səfərlər',

  // -------------------------------------------------------------- settings
  'settings': 'Tənzimləmələr',
  'language': 'Dil',
  'languageAz': 'Azərbaycan',
  'languageRu': 'Русский',
  'languageEn': 'English',
  'appearance': 'Görünüş',
  'themeSystem': 'Sistem',
  'themeLight': 'İşıqlı',
  'themeDark': 'Qaranlıq',
  'notificationSettings': 'Bildiriş tənzimləmələri',
  'pushNotifications': 'Push bildirişlər',
  'bookingNotifications': 'Bron bildirişləri',
  'messageNotifications': 'Mesaj bildirişləri',
  'reminderNotifications': 'Səfər xatırlatmaları',
  'marketingNotifications': 'Kampaniya və yeniliklər',
  'account': 'Hesab',
  'logout': 'Çıxış',
  'logoutConfirm': 'Hesabdan çıxmaq istəyirsiniz?',
  'deleteAccount': 'Hesabı sil',
  'deleteAccountTitle': 'Hesabı silmək',
  'deleteAccountWarning':
      'Hesabınız, elanlarınız və bron tarixçəniz həmişəlik silinəcək. Bu əməliyyat geri qaytarıla bilməz.',
  'deleteAccountConfirmHint': 'Təsdiq üçün SİL yazın',
  'deleteAccountKeyword': 'SİL',
  'accountDeleted': 'Hesab silindi',
  'support': 'Dəstək',
  'helpCenter': 'Yardım mərkəzi',
  'contactSupport': 'Bizimlə əlaqə',
  'rateApp': 'Tətbiqi qiymətləndir',
  'aboutApp': 'Tətbiq haqqında',
  'version': 'Versiya',
  'legal': 'Hüquqi',

  // ----------------------------------------------------------------- admin
  'adminPanel': 'Admin panel',
  'adminOverview': 'Ümumi baxış',
  'adminDocuments': 'Sənəd təsdiqi',
  'adminUsers': 'İstifadəçilər',
  'adminRides': 'Elanlar',
  'adminReports': 'Şikayətlər',
  'adminNoPending': 'Gözləyən sənəd yoxdur',
  'approve': 'Təsdiqlə',
  'block': 'Blokla',
  'unblock': 'Bloku aç',
  'blocked': 'Bloklanıb',
  'userBlocked': 'İstifadəçi bloklandı',
  'userUnblocked': 'İstifadəçinin bloku açıldı',
  'totalUsers': 'İstifadəçi',
  'totalDrivers': 'Sürücü',
  'totalRides': 'Elan',
  'totalBookings': 'Bron',
  'pendingVerifications': 'Gözləyən yoxlama',
  'openReports': 'Açıq şikayət',
  'reportUser': 'Şikayət et',
  'reportReason': 'Şikayət səbəbi',
  'reportSubmitted': 'Şikayətiniz göndərildi',
  'resolveReport': 'Həll edildi',
  'adminOnly': 'Bu bölmə yalnız adminlər üçündür',

  // ------------------------------------------------------------ validation
  'fieldRequired': 'Bu xana boş qala bilməz',
  'invalidPhone': 'Nömrə düzgün deyil',
  'invalidName': 'Ad ən azı 3 hərf olmalıdır',
  'invalidOtpFormat': 'Kod 6 rəqəm olmalıdır',
  'invalidPlate': 'Nömrə formatı: 10-AA-123',
  'invalidPrice': 'Qiymət 1–500 AZN aralığında olmalıdır',
  'invalidYear': 'İl düzgün deyil',
  'sameCityError': 'Başlanğıc və təyinat şəhəri eyni ola bilməz',
  'pastDateError': 'Keçmiş tarix seçilə bilməz',
  'tooFarDateError': 'Ən çox 3 ay sonraya elan verə bilərsiniz',
  'selectAtLeastOneSeat': 'Ən azı bir yer seçin',
  'commentTooLong': 'Şərh çox uzundur',

  // ---------------------------------------------------------------- errors
  'errNetwork': 'İnternet bağlantısı yoxdur',
  'errTimeout': 'Əməliyyat çox uzun çəkdi',
  'errServer': 'Serverdə xəta baş verdi',
  'errUnauthenticated': 'Sessiya bitib, yenidən daxil olun',
  'errPermissionDenied': 'Bu əməliyyat üçün icazəniz yoxdur',
  'errNotFound': 'Məlumat tapılmadı',
  'errAlreadyExists': 'Bu məlumat artıq mövcuddur',
  'errInvalidInput': 'Daxil edilən məlumat düzgün deyil',
  'errInvalidPhoneNumber': 'Telefon nömrəsi düzgün deyil',
  'errInvalidOtp': 'Kod yanlışdır',
  'errOtpExpired': 'Kodun müddəti bitib, yenisini alın',
  'errTooManyRequests': 'Çox cəhd etdiniz, bir az sonra yoxlayın',
  'errSeatsUnavailable': 'Kifayət qədər boş yer yoxdur',
  'errRideNotBookable': 'Bu elan artıq bron üçün açıq deyil',
  'errBookingNotCancellable': 'Bu bron ləğv edilə bilməz',
  'errSelfBooking': 'Öz elanınıza bron edə bilməzsiniz',
  'errDocumentsPending': 'Sənədləriniz hələ yoxlanılır',
  'errDocumentsRejected': 'Elan vermək üçün sənədləriniz təsdiqlənməlidir',
  'errStorage': 'Fayl yüklənə bilmədi',
  'errFileTooLarge': 'Fayl çox böyükdür. Daha kiçik şəkil seçin.',
  'errCancelled': 'Əməliyyat dayandırıldı',
  'errUnknown': 'Gözlənilməz xəta baş verdi',
  'errorTitle': 'Nəsə səhv getdi',

  // ------------------------------------------------------------ navigation
  'navSearch': 'Axtarış',
  'navRides': 'Elanlar',
  'navBookings': 'Bronlar',
  'navChat': 'Söhbət',
  'navProfile': 'Profil',
  'navPublish': 'Elan ver',
  'navRequests': 'Sorğular',

  // ------------------------------------------------- API-specific
  'filtersLocalNote':
      'Qiymət və vaxt filtrləri yalnız yüklənmiş nəticələrə tətbiq olunur.',
  'alreadyRequestedTitle': 'Artıq müraciət etmisiniz',
  'alreadyRequestedBody':
      'Bu səfərdə ya aktiv bronunuz var, ya da sürücü artıq qərarını verib. Eyni istiqamətdə başqa səfərlərə baxa bilərsiniz.',
  'alreadyReviewedBody': 'Bu səfər üçün rəyinizi artıq yazmısınız.',
  'conversationLocked': 'Bron ləğv olunduğu üçün bu söhbət bağlanıb.',
  'linkUnavailableTitle': 'Artıq mövcud deyil',
  'linkUnavailableBody': 'Bu bildirişin aid olduğu səfər və ya bron silinib.',
  'loadMore': 'Daha çox yüklə',
  'documentsNoPreview': 'Yüklənmiş sənədlər təhlükəsizlik üçün göstərilmir.',
  'seatsIncludeDriver': 'Sürücü daxil ümumi yer sayı',
  'plateVisibleToYou': 'Nömrə yalnız sizə görünür',
  'routeNotEditable':
      'Marşrut və avtomobil dərc edildikdən sonra dəyişdirilə bilməz.',
  'cancelRide': 'Səfəri ləğv et',
  'cancelRideConfirm':
      'Bu səfər ləğv olunacaq və bütün gözləyən və təsdiqlənmiş bronlar avtomatik ləğv ediləcək. Sərnişinlərə bildiriş gedəcək.',
  'dropoffPointHint': 'Məs. Qəbələ mərkəz',
  'city': 'Şəhər',
  'birthYear': 'Doğum ili',
  'docBothSides': 'Hər iki üzün şəklini əlavə edin, sonra göndərin.',
  'docFrontSide': 'Ön üz',
  'docBackSide': 'Arxa üz',
  'docPhoto': 'Sənədin şəkli',
  'docAddPhoto': 'Şəkil əlavə et',
  'docTapToChange': 'Dəyişmək üçün toxun',
  'docUnsupportedFormat':
      'Bu şəkil formatı dəstəklənmir. JPG və ya PNG şəkil seçin.',
  'devCodeTitle': 'SMS hələ qoşulmayıb',
  'devCodeBody':
      'Kodu server birbaşa cavabda qaytarır. Toxun — xanalara özü yazılacaq.',
  'chooseModeTitle': 'Necə davam edirsən?',
  'chooseModeBody':
      'Bu seçimlə başlayacaqsan. Sonra Profil bölməsindən istədiyin vaxt dəyişə bilərsən.',
  'driverModeNeedsVehicle':
      'Sürücü rejimi üçün avtomobil lazımdır. Hesabında avtomobil yoxdursa, tətbiq sərnişin rejimində açılacaq — Profil → Avtomobil bölməsindən əlavə etdiyin an sürücü rejiminə keçəcək.',

  // ------------------------------------------------------- tətbiq yeniləməsi
  'updateRequiredTitle': 'Yeniləmə tələb olunur',
  'updateRequiredBody':
      'Bu versiya artıq dəstəklənmir. Davam etmək üçün tətbiqi yeniləyin.',
  'updateOptionalTitle': 'Yeni versiya hazırdır',
  'updateOptionalBody':
      'Yeniliklər və düzəlişlər səni gözləyir. Yeniləmək bir neçə saniyə çəkir.',
  'updateNow': 'Yenilə',
  'updateLater': 'Sonra',
  'updateStoreUnavailable':
      'Mağazanı aça bilmədik. Yeniləməni mağazada əl ilə axtar.',

  // --------------------------------------------------- böyümə funksiyaları
  'rideRequests': 'Tələb elanları',
  'myRideRequests': 'Axtardıqlarım',
  'createRideRequest': 'Bu marşrut üçün elan yarat',
  'createRideRequestTitle': 'Nə axtarırsan?',
  'createRideRequestBody':
      'Marşrutu yaz — həmin yolu sürən sürücülərə çatdıraq. Uyğun səfər yarananda sənə xəbər verəcəyik.',
  'rideRequestCreated': 'Tələbin sürücülərə çatdı',
  'rideRequestCreatedBody':
      'Bu marşrutda səfər yaranan kimi bildiriş göndərəcəyik.',
  'rideRequestCancelled': 'Tələb bağlandı',
  'rideRequestCancel': 'Tələbi bağla',
  'rideRequestCancelConfirm': 'Bu tələb elanını bağlayaq?',
  'rideRequestMatches': 'Uyğun səfərlər',
  'rideRequestNoMatches': 'Hələ uyğun səfər yoxdur',
  'rideRequestNoMatchesBody':
      'Sürücülərə xəbər verdik. Səfər yaranan kimi bildiriş alacaqsan.',
  'noRideRequests': 'Açıq tələbin yoxdur',
  'noRideRequestsBody':
      'Axtardığın marşrutda səfər tapmasan, tələb elanı yarat — sürücülər görsün.',
  'incomingRideRequests': 'Marşrutunda axtaranlar',
  'incomingRideRequestsBody':
      'Bu adamlar sənin sürdüyün marşrutda yer axtarır. Elan ver — səni görsünlər.',
  'noIncomingRideRequests': 'Hazırda açıq tələb yoxdur',
  'noIncomingRideRequestsBody':
      'Marşrutunda kimsə yer axtaranda burada görünəcək.',
  'flexibleDays': 'Tarix çevikliyi',
  'flexibleDaysExact': 'Dəqiq tarix',
  'wantedDate': 'Gediş tarixi',
  'requestNoteHint': 'Sürücüyə əlavə söz (istəyə bağlı)',
  'publishForThisRequest': 'Bu marşrutda elan ver',
  'rideRequestStatusOpen': 'Gözləyir',
  'rideRequestStatusFulfilled': 'Səfər tapıldı',
  'rideRequestStatusCancelled': 'Bağlanıb',
  'rideRequestStatusExpired': 'Vaxtı keçib',
  'demandTitle': 'Marşrutunda tələb',
  'demandEmpty': 'Bu marşrutda hələ kifayət qədər hərəkət yoxdur',
  'topRoutesTitle': 'Ən çox axtarılan marşrutlar',
  'topRoutesBody': 'Bu marşrutlarda tələb təklifdən çoxdur.',
  'demandPublishCta': 'Elan ver',
  'earningsTitle': 'Qazancın',
  'earningsFuelNote': 'Bu marşrutun təxmini yanacaq xərci',
  'earningsFree': 'Komissiya yoxdur — qazancın hamısı sənindir.',
  'suggestedPrice': 'Təklif olunan qiymət',
  'suggestedPriceHistory': 'Bu marşrutdakı elanların ortası',
  'suggestedPriceDistance': 'Məsafəyə görə təxmin',
  'usePrice': 'Bu qiyməti seç',
  'womenOnly': 'Yalnız qadın sərnişin',
  'womenOnlyRide': 'Qadın sərnişinlər üçün',
  'womenOnlyHint':
      'Bu səfərə yalnız qadın sərnişinlər müraciət edə bilər. Yalnız qadın sürücülər seçə bilər.',
  'womenOnlyBlocked': 'Bu səfər yalnız qadın sərnişinlər üçündür.',
  'filterDriverGender': 'Sürücünün cinsi',
  'filterDriverAny': 'Fərq etməz',
  'filterDriverFemale': 'Qadın sürücü',
  'filterDriverMale': 'Kişi sürücü',
  'filterInstantOnly': 'Yalnız ani bron',
  'filterVerifiedOnly': 'Yalnız təsdiqlənmiş sürücü',
  'filterWomenOnly': 'Yalnız qadın səfərləri',
  'filterServerNote':
      'Bu filtrlər serverdə tətbiq olunur — nəticələr yenidən yüklənəcək.',
  'verifiedDriver': 'Təsdiqlənmiş sürücü',
  'tierTrusted': 'Etibarlı sürücü',
  'tierRising': 'Yüksələn sürücü',
  'verifyBoostHint':
      'Sənədləri təsdiqlənmiş sürücülərin elanları daha çox bron alır.',
  'repeatRide': 'Təkrar elan ver',
  'repeatRideTitle': 'Eyni səfəri təkrarla',
  'repeatRideBody': 'Marşrut, qiymət və yer sayı olduğu kimi qalır.',
  'repeatWeeks': 'Neçə həftə',
  'repeatWeeksOnce': 'Yalnız bu dəfə',
  'repeatCreated': 'Elan verildi',
  'shareRide': 'Səfəri paylaş',
  'shareRideUnavailable': 'Bu səfərin paylaşma linki yoxdur',
  'referral': 'Dostunu dəvət et',
  'referralTitle': 'Dəvət et, elanların yuxarı çıxsın',
  'referralBody':
      'Dəvət etdiyin adam ilk səfərini edəndə elanların bir həftə axtarışın başında görünür.',
  'referralCode': 'Dəvət kodun',
  'referralInvited': 'Dəvət etdiklərin',
  'referralActive': 'Səfər edənlər',
  'referralBoostActive': 'Elanların yuxarıdadır',
  'referralBoostUntil': 'Bitmə tarixi',
  'referralShare': 'Kodu paylaş',
  'referralShareText':
      'Yol Yoldaşı ilə şəhərlərarası səfər et. Qeydiyyatda mənim kodumu yaz:',
  'referralCodeHint': 'Dəvət kodu (istəyə bağlı)',
  'switchMode': 'Rejimi dəyiş',
  'switchToDriver': 'Sürücü rejiminə keç',
  'switchToPassenger': 'Sərnişin rejiminə keç',
  'switchModeConfirmDriver':
      'Sürücü rejiminə keçirsən. Elan vermək və gələn bronları idarə etmək mümkün olacaq.',
  'switchModeConfirmPassenger':
      'Sərnişin rejiminə keçirsən. Səfər axtarıb yer bron edə biləcəksən.',
  'switchModeDone': 'Rejim dəyişdi',
  'becomeDriverTitle': 'Sən də sürücü ola bilərsən',
  'becomeDriverBody':
      'Rayona gedirsən? Boş yerlərini paylaş, yol xərcini azalt. Komissiya yoxdur.',
  'signInToContinue': 'Davam etmək üçün daxil ol',
  'signInToBook': 'Yer bron etmək üçün daxil ol',
  'signInToRequest': 'Tələb elanı yaratmaq üçün daxil ol',
  'browseAsGuest': 'Əvvəlcə səfərlərə bax',
  'signIn': 'Daxil ol',
  'errDriverProfileRequired': 'Sürücü rejimi üçün əvvəlcə avtomobil əlavə et.',
  'errWomenOnlyRide': 'Bu səfər yalnız qadın sərnişinlər üçündür.',
  'notifRideRequestMatchedTitle': 'Axtardığın marşrutda səfər var',
  'notifRideRequestPostedTitle': 'Marşrutunda sərnişin axtarır',
  'skipSignIn': 'Lazım deyil',
  'askDriversTitle': 'Axtardığını tapmırsan?',
  'askDriversBody': 'Marşrutunu yaz — həmin yolu sürən sürücülərə çatdıraq.',
  'countryCodeTitle': 'Ölkə kodu',
  'countrySearchHint': 'Ölkə və ya kod axtar',
  'countryNotFound': 'Belə ölkə tapılmadı',
};
