/// Russian strings. Key set must match `kStringsAz`.
const Map<String, String> kStringsRu = {
  // ---------------------------------------------------------------- general
  'appName': 'Yol Yoldaşı',
  'appTagline': 'Поедем вместе между городами',
  'ok': 'Ок',
  'cancel': 'Отмена',
  'save': 'Сохранить',
  'delete': 'Удалить',
  'edit': 'Изменить',
  'retry': 'Повторить',
  'next': 'Далее',
  'back': 'Назад',
  'skip': 'Пропустить',
  'done': 'Готово',
  'close': 'Закрыть',
  'search': 'Поиск',
  'confirm': 'Подтвердить',
  'reject': 'Отклонить',
  'yes': 'Да',
  'no': 'Нет',
  'loading': 'Загрузка…',
  'seeAll': 'Показать все',
  'clear': 'Очистить',
  'apply': 'Применить',
  'reset': 'Сбросить',
  'optional': 'необязательно',
  'continueLabel': 'Продолжить',
  'share': 'Поделиться',
  'copy': 'Копировать',
  'copied': 'Скопировано',
  'today': 'Сегодня',
  'tomorrow': 'Завтра',
  'yesterday': 'Вчера',
  'from': 'Откуда',
  'to': 'Куда',
  'currency': 'AZN',
  'perSeat': 'за место',
  'rating': 'Рейтинг',
  'noResultsTitle': 'Ничего не найдено',
  'noResultsBody': 'Измените параметры поиска и попробуйте снова.',
  'emptyTitle': 'Пока пусто',
  'refresh': 'Обновить',
  'showMore': 'Показать больше',
  'showLess': 'Свернуть',
  'anonymous': 'Аноним',
  'you': 'Вы',
  'now': 'сейчас',
  'unknown': 'Неизвестно',

  // ------------------------------------------------------------ onboarding
  'onboard1Title': 'Найдите попутчика',
  'onboard1Body':
      'Из Баку в Гянджу, из Шеки в Лянкяран — соединяем водителей и пассажиров, которым по пути.',
  'onboard2Title': 'Разделите расходы',
  'onboard2Body':
      'Публикуйте свободные места и делите стоимость топлива. Для пассажира — часть цены такси.',
  'onboard3Title': 'Безопасно и прозрачно',
  'onboard3Body':
      'Документы водителей проверяются, после поездки — взаимные оценки. Номер открывается только после подтверждения брони.',
  'getStarted': 'Начать',

  // ------------------------------------------------------------------ auth
  'loginTitle': 'Добро пожаловать',
  'loginSubtitle': 'Введите номер — отправим код подтверждения по SMS.',
  'phoneNumber': 'Номер телефона',
  'phoneHint': '50 123 45 67',
  'sendCode': 'Отправить код',
  'termsPrefix': 'Продолжая, вы соглашаетесь с ',
  'termsOfUse': 'условиями использования',
  'termsAnd': ' и ',
  'privacyPolicy': 'политикой конфиденциальности',
  'termsSuffix': '.',
  'otpTitle': 'Введите код',
  'changeNumber': 'Изменить номер',
  'resendCode': 'Отправить код повторно',
  'resendIn': 'Отправить повторно',
  'verify': 'Подтвердить',
  'otpAutoHint': 'Код будет прочитан автоматически',
  'signingIn': 'Выполняется вход…',

  // ------------------------------------------------------------------ role
  'roleTitle': 'Как будете пользоваться?',
  'roleSubtitle': 'Это можно изменить в любой момент.',
  'driver': 'Водитель',
  'passenger': 'Пассажир',
  'driverRoleDesc': 'Публикую маршруты и делюсь свободными местами.',
  'passengerRoleDesc': 'Ищу поездку и бронирую место.',
  'driverMode': 'Режим водителя',
  'passengerMode': 'Режим пассажира',
  'activeMode': 'Режим',

  // --------------------------------------------------------------- profile
  'profile': 'Профиль',
  'profileSetupTitle': 'Расскажите о себе',
  'profileSetupSubtitle': 'Имя и фото вызывают доверие у попутчиков.',
  'fullName': 'Имя и фамилия',
  'fullNameHint': 'Например: Рашад Алиев',
  'about': 'О себе',
  'aboutHint': 'Пара слов о себе…',
  'gender': 'Пол',
  'male': 'Мужской',
  'female': 'Женский',
  'genderUnspecified': 'Не указывать',
  'photo': 'Фото',
  'addPhoto': 'Добавить фото',
  'changePhoto': 'Изменить фото',
  'removePhoto': 'Удалить фото',
  'takePhoto': 'Сделать снимок',
  'pickFromGallery': 'Выбрать из галереи',
  'editProfile': 'Редактировать профиль',
  'memberSince': 'Регистрация',
  'completedTrips': 'Завершённых поездок',
  'profileSaved': 'Профиль обновлён',
  'verifiedBadge': 'Проверен',
  'phoneVerified': 'Номер подтверждён',

  // --------------------------------------------------------------- vehicle
  'vehicle': 'Автомобиль',
  'vehicleInfo': 'Данные автомобиля',
  'vehicleBrand': 'Марка',
  'vehicleBrandHint': 'Например: Mercedes-Benz',
  'vehicleModel': 'Модель',
  'vehicleModelHint': 'Например: E 200',
  'vehicleColor': 'Цвет',
  'vehiclePlate': 'Госномер',
  'vehiclePlateHint': '10-AA-123',
  'vehicleYear': 'Год выпуска',
  'vehicleSeats': 'Пассажирских мест',
  'saveVehicle': 'Сохранить автомобиль',
  'vehicleSaved': 'Данные автомобиля сохранены',
  'noVehicle': 'Автомобиль не добавлен',

  // ------------------------------------------------------------- documents
  'documents': 'Документы',
  'documentsTitle': 'Документы водителя',
  'documentsSubtitle':
      'Чтобы публиковать объявления, документы должны пройти проверку. Обычно это занимает до 24 часов.',
  'docIdCard': 'Удостоверение личности',
  'docDriverLicense': 'Водительское удостоверение',
  'docVehicleRegistration': 'Свидетельство о регистрации ТС',
  'docInsurance': 'Обязательная страховка',
  'docIdCardDesc': 'Лицевая и обратная стороны должны быть читаемы.',
  'docDriverLicenseDesc': 'Срок действия не должен быть истёкшим.',
  'docVehicleRegistrationDesc': 'Свидетельство о регистрации автомобиля.',
  'docInsuranceDesc': 'Полис обязательного страхования.',
  'uploadDocument': 'Загрузить документ',
  'replaceDocument': 'Заменить документ',
  'docStatusNotUploaded': 'Не загружено',
  'docStatusPending': 'На проверке',
  'docStatusApproved': 'Подтверждено',
  'docStatusRejected': 'Отклонено',
  'verificationPending': 'Документы на проверке',
  'verificationPendingBody':
      'До завершения проверки публикация объявлений недоступна.',
  'verificationApproved': 'Статус водителя подтверждён',
  'verificationRejected': 'Документы отклонены',
  'verificationRejectedBody':
      'Прочитайте причину и загрузите документы заново.',
  'rejectionReason': 'Причина отказа',
  'submitForReview': 'Отправить на проверку',
  'documentsSubmitted': 'Документы отправлены на проверку',
  'allDocumentsRequired': 'Загрузите все документы',

  // ------------------------------------------------------------------ ride
  'publishRide': 'Разместить объявление',
  'publishRideShort': 'Разместить',
  'editRide': 'Изменить объявление',
  'routeStep': 'Маршрут',
  'scheduleStep': 'Дата и время',
  'detailsStep': 'Условия',
  'fromCity': 'Откуда',
  'toCity': 'Куда',
  'selectCity': 'Выберите город',
  'searchCity': 'Поиск города',
  'swapCities': 'Поменять местами',
  'date': 'Дата',
  'time': 'Время',
  'selectDate': 'Выберите дату',
  'selectTime': 'Выберите время',
  'seatsAvailable': 'Свободных мест',
  'pricePerSeat': 'Цена за место',
  'priceHint': 'Например: 15',
  'rideNote': 'Дополнительно',
  'rideNoteHint': 'Место остановки, багаж, курение и т. д.',
  'pickupPoint': 'Место встречи',
  'pickupPointHint': 'Например: метро 20 Января',
  'dropoffPoint': 'Место высадки',
  'publish': 'Опубликовать',
  'ridePublished': 'Объявление опубликовано',
  'rideUpdated': 'Объявление обновлено',
  'rideDeleted': 'Объявление удалено',
  'deleteRideConfirm': 'Удалить объявление?',
  'deleteRideWithBookings':
      'По этому объявлению есть подтверждённые брони. Свяжитесь с пассажирами вместо удаления.',
  'myRides': 'Мои объявления',
  'activeRides': 'Активные',
  'pastRides': 'Прошедшие',
  'rideActive': 'Активно',
  'rideInactive': 'Неактивно',
  'rideCompleted': 'Завершено',
  'rideCancelled': 'Отменено',
  'activateRide': 'Активировать',
  'deactivateRide': 'Деактивировать',
  'rideDetails': 'О поездке',
  'noRidesYet': 'Объявлений пока нет',
  'noRidesYetBody':
      'Опубликуйте первый маршрут и поделитесь свободными местами.',
  'rideFull': 'Мест нет',
  'departure': 'Отправление',
  'instantBooking': 'Мгновенная бронь',
  'instantBookingDesc': 'Брони подтверждаются автоматически',
  'requestBooking': 'Бронь по запросу',
  'requestBookingDesc': 'Вы подтверждаете каждую бронь сами',

  // ---------------------------------------------------------------- search
  'searchTitle': 'Куда едете?',
  'searchRides': 'Найти поездку',
  'anyDate': 'Любая дата',
  'passengersCount': 'Количество пассажиров',
  'searchResults': 'Результаты поиска',
  'filters': 'Фильтры',
  'sortBy': 'Сортировка',
  'sortEarliest': 'Раньше всех',
  'sortCheapest': 'Дешевле',
  'sortTopRated': 'Высокий рейтинг',
  'priceRange': 'Диапазон цен',
  'timeOfDay': 'Время суток',
  'morning': 'Утро',
  'afternoon': 'День',
  'evening': 'Вечер',
  'night': 'Ночь',
  'onlyVerified': 'Только проверенные водители',
  'noRidesFound': 'На этом маршруте поездок нет',
  'noRidesFoundBody': 'Попробуйте изменить дату или настроить уведомление.',
  'recentSearches': 'Недавние поиски',
  'popularRoutes': 'Популярные маршруты',
  'allActiveRides': 'Все активные поездки',
  'noActiveRides': 'Сейчас активных поездок нет',
  'noActiveRidesBody': 'Новые объявления появятся здесь сразу.',

  // --------------------------------------------------------------- booking
  'bookSeat': 'Забронировать',
  'bookingTitle': 'Бронь',
  'howManySeats': 'Сколько мест нужно?',
  'totalPrice': 'Итого',
  'messageToDriver': 'Сообщение водителю',
  'messageToDriverHint': 'Здравствуйте, где встретимся?',
  'sendRequest': 'Отправить запрос',
  'bookNow': 'Забронировать сейчас',
  'bookingSent': 'Запрос на бронь отправлен',
  'bookingConfirmedToast': 'Бронь подтверждена',
  'myBookings': 'Мои брони',
  'bookingRequests': 'Запросы на бронь',
  'upcoming': 'Предстоящие',
  'history': 'История',
  'statusPending': 'Ожидает',
  'statusConfirmed': 'Подтверждено',
  'statusRejected': 'Отклонено',
  'statusCancelledByPassenger': 'Отменено пассажиром',
  'statusCancelledByDriver': 'Отменено водителем',
  'statusCompleted': 'Завершено',
  'cancelBooking': 'Отменить бронь',
  'cancelBookingConfirm': 'Отменить бронь?',
  'bookingCancelled': 'Бронь отменена',
  'keepBooking': 'Оставить бронь',
  'cancelReleasesSeat':
      'Ваше место освободится сразу. Если передумаете, можно забронировать снова — но к тому времени место может уйти.',
  'rebookSameRide': 'Забронировать снова',
  'rebookSameRideBody':
      'Вы отменили эту поездку. Если место ещё свободно, его можно забронировать снова.',
  'rideClosedToYou': 'Эта поездка вам закрыта',
  'rideClosedToYouBody':
      'Водитель принял решение, поэтому подать заявку на эту поездку снова нельзя. Посмотрите другие поездки по тому же маршруту.',
  'seatTakenAlready': 'Место уже занято',
  'seatTakenAlreadyBody':
      'После вашей отмены место занял другой пассажир. Посмотрите другие поездки по тому же маршруту.',
  'blockPassenger': 'Закрыть поездку для пассажира',
  'blockPassengerConfirm':
      'Этот пассажир больше не сможет забронировать эту поездку. Вы можете снова открыть её в любой момент.',
  'passengerBlocked': 'Поездка закрыта для пассажира',
  'passengerBlockedBody':
      'После отмены вы закрыли для него эту поездку — забронировать снова он не может.',
  'unblockPassenger': 'Открыть снова',
  'passengerBlockedMsg': 'Поездка закрыта для этого пассажира',
  'passengerUnblockedMsg': 'Поездка снова открыта для этого пассажира',
  'lateCancellationWarning':
      'До отправления мало времени — отмена сейчас подводит другую сторону.',
  'cancelReasonQuestion': 'Почему вы отменяете?',
  'cancelReasonPlanChanged': 'Мои планы изменились',
  'cancelReasonFoundCheaper': 'Нашёл поездку дешевле',
  'cancelReasonNoAnswer': 'Водитель не отвечает',
  'cancelReasonVehicleProblem': 'Проблема с автомобилем',
  'cancelReasonRescheduled': 'Я изменил время поездки',
  'cancelReasonOther': 'Другая причина',
  'cancelReasonHint': 'Кратко опишите (необязательно)',
  'cancellationReasonTitle': 'Причина отмены',
  'findAnotherRide': 'Найти другую поездку',
  'findAnotherRideBody':
      'Повторно подать заявку на эту поездку нельзя, но можно посмотреть самые дешёвые поездки по тому же маршруту.',
  'confirmBooking': 'Подтвердить',
  'rejectBooking': 'Отклонить',
  'bookingConfirmedMsg': 'Бронь подтверждена, пассажир уведомлён.',
  'bookingRejectedMsg': 'Бронь отклонена.',
  'noBookingsYet': 'Броней пока нет',
  'noBookingsYetBody': 'Найдите поездку и забронируйте первое место.',
  'noRequestsYet': 'Запросов пока нет',
  'noRequestsYetBody': 'Запросы по вашим объявлениям появятся здесь.',
  'seatsBooked': 'Забронировано мест',
  'bookedBy': 'Забронировал',
  'markCompleted': 'Завершить поездку',
  'tripCompleted': 'Поездка завершена',

  // --------------------------------------------------------------- contact
  'contact': 'Контакт',
  'callDriver': 'Позвонить водителю',
  'callPassenger': 'Позвонить пассажиру',
  'sendMessage': 'Написать',
  'phoneHiddenTitle': 'Номер скрыт',
  'phoneHiddenBody':
      'В целях безопасности номер открывается только после подтверждения брони.',
  'openWhatsapp': 'Написать в WhatsApp',
  'cannotCall': 'Не удалось начать звонок',

  // ------------------------------------------------------------------ chat
  'chat': 'Чат',
  'messages': 'Сообщения',
  'typeMessage': 'Введите сообщение…',
  'noMessages': 'Сообщений пока нет',
  'noMessagesBody': 'Уточните детали поездки здесь.',
  'noConversations': 'Чатов нет',
  'noConversationsBody': 'Чат открывается после подтверждения брони.',
  'chatLockedTitle': 'Чат закрыт',
  'chatLockedBody': 'Писать можно после подтверждения брони.',

  // --------------------------------------------------------- notifications
  'notifications': 'Уведомления',
  'markAllRead': 'Отметить все прочитанными',
  'noNotifications': 'Уведомлений нет',
  'noNotificationsBody': 'Здесь появятся новости о бронях и поездках.',
  'notifNewBookingTitle': 'Новый запрос на бронь',
  'notifBookingConfirmedTitle': 'Ваша бронь подтверждена',
  'notifBookingRejectedTitle': 'Ваша бронь отклонена',
  'notifBookingCancelledTitle': 'Бронь отменена',
  'notifRideReminderTitle': 'Напоминание о поездке',
  'notifRideCancelledTitle': 'Поездка отменена',
  'notifNewMessageTitle': 'Новое сообщение',
  'notifReviewRequestTitle': 'Оцените поездку',
  'notifDocsApprovedTitle': 'Документы подтверждены',
  'notifDocsRejectedTitle': 'Документы отклонены',
  'notifAdminMessageTitle': 'Сервисное уведомление',
  'notifAdminMarketingTitle': 'Акция',
  'notifUnknownTitle': 'Новое уведомление',

  // Каналы уведомлений Android — под этими именами они видны в настройках.
  'channelMessages': 'Сообщения',
  'channelMessagesDesc': 'Новые сообщения в чатах',
  'channelBookings': 'Брони',
  'channelBookingsDesc': 'Запросы, подтверждения и отмены броней',
  'channelReminders': 'Напоминания о поездке',
  'channelRemindersDesc': 'Напоминание перед отправлением',
  'channelMarketing': 'Акции',
  'channelMarketingDesc': 'Скидки и новости',
  'channelGeneral': 'Общие',
  'channelGeneralDesc': 'Уведомления аккаунта и прочее',

  // --------------------------------------------------------------- reviews
  'reviews': 'Отзывы',
  'rateTrip': 'Оцените поездку',
  'rateTripSubtitle': 'Ваш отзыв помогает другим пользователям.',
  'yourRating': 'Ваша оценка',
  'writeComment': 'Напишите отзыв',
  'writeCommentHint': 'Как прошла поездка?',
  'submitReview': 'Отправить отзыв',
  'reviewSubmitted': 'Спасибо за отзыв',
  'noReviews': 'Отзывов пока нет',
  'noReviewsBody': 'Напишите первый отзыв.',
  'ratingPoor': 'Плохо',
  'ratingFair': 'Нормально',
  'ratingGood': 'Хорошо',
  'ratingVeryGood': 'Очень хорошо',
  'ratingExcellent': 'Отлично',
  'reviewsAsDriver': 'Как водитель',
  'reviewsAsPassenger': 'Как пассажир',
  'pendingReviews': 'Неоценённые поездки',

  // -------------------------------------------------------------- settings
  'settings': 'Настройки',
  'language': 'Язык',
  'languageAz': 'Azərbaycan',
  'languageRu': 'Русский',
  'languageEn': 'English',
  'appearance': 'Оформление',
  'themeSystem': 'Системная',
  'themeLight': 'Светлая',
  'themeDark': 'Тёмная',
  'notificationSettings': 'Настройки уведомлений',
  'pushNotifications': 'Push-уведомления',
  'bookingNotifications': 'Уведомления о бронях',
  'messageNotifications': 'Уведомления о сообщениях',
  'reminderNotifications': 'Напоминания о поездках',
  'marketingNotifications': 'Акции и новости',
  'account': 'Аккаунт',
  'logout': 'Выйти',
  'logoutConfirm': 'Выйти из аккаунта?',
  'deleteAccount': 'Удалить аккаунт',
  'deleteAccountTitle': 'Удаление аккаунта',
  'deleteAccountWarning':
      'Ваш аккаунт, объявления и история броней будут удалены навсегда. Отменить это действие нельзя.',
  'deleteAccountConfirmHint': 'Для подтверждения введите УДАЛИТЬ',
  'deleteAccountKeyword': 'УДАЛИТЬ',
  'accountDeleted': 'Аккаунт удалён',
  'support': 'Поддержка',
  'helpCenter': 'Центр помощи',
  'contactSupport': 'Связаться с нами',
  'rateApp': 'Оценить приложение',
  'aboutApp': 'О приложении',
  'version': 'Версия',
  'legal': 'Правовая информация',

  // ----------------------------------------------------------------- admin
  'adminPanel': 'Админ-панель',
  'adminOverview': 'Обзор',
  'adminDocuments': 'Проверка документов',
  'adminUsers': 'Пользователи',
  'adminRides': 'Объявления',
  'adminReports': 'Жалобы',
  'adminNoPending': 'Документов на проверке нет',
  'approve': 'Одобрить',
  'block': 'Заблокировать',
  'unblock': 'Разблокировать',
  'blocked': 'Заблокирован',
  'userBlocked': 'Пользователь заблокирован',
  'userUnblocked': 'Пользователь разблокирован',
  'totalUsers': 'Пользователей',
  'totalDrivers': 'Водителей',
  'totalRides': 'Объявлений',
  'totalBookings': 'Броней',
  'pendingVerifications': 'Ожидают проверки',
  'openReports': 'Открытых жалоб',
  'reportUser': 'Пожаловаться',
  'reportReason': 'Причина жалобы',
  'reportSubmitted': 'Жалоба отправлена',
  'resolveReport': 'Решено',
  'adminOnly': 'Этот раздел только для администраторов',

  // ------------------------------------------------------------ validation
  'fieldRequired': 'Это поле обязательно',
  'invalidPhone': 'Некорректный номер',
  'invalidName': 'Имя должно содержать минимум 3 буквы',
  'invalidOtpFormat': 'Код должен состоять из 6 цифр',
  'invalidPlate': 'Формат номера: 10-AA-123',
  'invalidPrice': 'Цена должна быть от 1 до 500 AZN',
  'invalidYear': 'Некорректный год',
  'sameCityError': 'Город отправления и назначения не могут совпадать',
  'pastDateError': 'Нельзя выбрать прошедшую дату',
  'tooFarDateError': 'Объявление можно разместить максимум на 3 месяца вперёд',
  'selectAtLeastOneSeat': 'Выберите хотя бы одно место',
  'commentTooLong': 'Отзыв слишком длинный',

  // ---------------------------------------------------------------- errors
  'errNetwork': 'Нет подключения к интернету',
  'errTimeout': 'Операция заняла слишком много времени',
  'errServer': 'Ошибка на сервере',
  'errUnauthenticated': 'Сессия истекла, войдите заново',
  'errPermissionDenied': 'У вас нет прав на это действие',
  'errNotFound': 'Данные не найдены',
  'errAlreadyExists': 'Такая запись уже существует',
  'errInvalidInput': 'Введённые данные некорректны',
  'errInvalidPhoneNumber': 'Некорректный номер телефона',
  'errInvalidOtp': 'Неверный код',
  'errOtpExpired': 'Срок действия кода истёк, запросите новый',
  'errTooManyRequests': 'Слишком много попыток, повторите позже',
  'errSeatsUnavailable': 'Недостаточно свободных мест',
  'errRideNotBookable': 'Это объявление больше не доступно для брони',
  'errBookingNotCancellable': 'Эту бронь нельзя отменить',
  'errSelfBooking': 'Нельзя забронировать собственное объявление',
  'errDocumentsPending': 'Ваши документы ещё проверяются',
  'errDocumentsRejected': 'Для публикации документы должны быть подтверждены',
  'errStorage': 'Не удалось загрузить файл',
  'errCancelled': 'Операция прервана',
  'errUnknown': 'Произошла непредвиденная ошибка',
  'errorTitle': 'Что-то пошло не так',

  // ------------------------------------------------------------ navigation
  'navSearch': 'Поиск',
  'navRides': 'Объявления',
  'navBookings': 'Брони',
  'navChat': 'Чат',
  'navProfile': 'Профиль',
  'navPublish': 'Разместить',
  'navRequests': 'Запросы',

  // ------------------------------------------------- API-specific
  'filtersLocalNote':
      'Фильтры по цене и времени применяются только к загруженным результатам.',
  'alreadyRequestedTitle': 'Вы уже подавали заявку',
  'alreadyRequestedBody':
      'У вас либо уже есть бронь на эту поездку, либо водитель принял решение. Посмотрите другие поездки по тому же маршруту.',
  'alreadyReviewedBody': 'Вы уже оставили отзыв об этой поездке.',
  'conversationLocked': 'Чат закрыт, так как бронь отменена.',
  'linkUnavailableTitle': 'Больше недоступно',
  'linkUnavailableBody':
      'Поездка или бронь, к которой относится это уведомление, удалена.',
  'loadMore': 'Загрузить ещё',
  'documentsNoPreview':
      'Загруженные документы не показываются в целях безопасности.',
  'seatsIncludeDriver': 'Всего мест, включая водителя',
  'plateVisibleToYou': 'Номер виден только вам',
  'routeNotEditable': 'Маршрут и автомобиль нельзя изменить после публикации.',
  'cancelRide': 'Отменить поездку',
  'cancelRideConfirm':
      'Поездка будет отменена, а все ожидающие и подтверждённые брони — автоматически отменены. Пассажиры получат уведомление.',
  'dropoffPointHint': 'Напр. центр Габалы',
  'city': 'Город',
  'birthYear': 'Год рождения',
  'docBackSideRequired':
      'Для этого документа нужны обе стороны — загрузка отменена.',
  'docBothSides': 'Сначала выберите лицевую сторону, затем обратную.',
  'devCodeTitle': 'SMS ещё не подключён',
  'devCodeBody':
      'Сервер возвращает код прямо в ответе. Нажмите — он подставится в поля.',
  'chooseModeTitle': 'Как продолжить?',
  'chooseModeBody':
      'Вы продолжите в выбранном режиме. Чтобы сменить его, выйдите и войдите заново.',
  'driverModeNeedsVehicle':
      'Для режима водителя нужен автомобиль. Без него приложение откроется в режиме пассажира и переключится само, как только вы добавите машину в «Профиль → Автомобиль».',

  // ------------------------------------------------ обновление приложения
  'updateRequiredTitle': 'Требуется обновление',
  'updateRequiredBody':
      'Эта версия больше не поддерживается. Чтобы продолжить, обновите приложение.',
  'updateOptionalTitle': 'Доступна новая версия',
  'updateOptionalBody':
      'Вас ждут улучшения и исправления. Обновление занимает несколько секунд.',
  'updateNow': 'Обновить',
  'updateLater': 'Позже',
  'updateStoreUnavailable':
      'Не удалось открыть магазин. Найдите обновление в нём вручную.',
};
