/// English strings. Key set must match `kStringsAz`.
const Map<String, String> kStringsEn = {
  // ---------------------------------------------------------------- general
  'appName': 'Yol Yoldaşı',
  'appTagline': 'Share the road between cities',
  'ok': 'OK',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'retry': 'Retry',
  'next': 'Next',
  'back': 'Back',
  'skip': 'Skip',
  'done': 'Done',
  'close': 'Close',
  'search': 'Search',
  'confirm': 'Confirm',
  'reject': 'Decline',
  'yes': 'Yes',
  'no': 'No',
  'loading': 'Loading…',
  'seeAll': 'See all',
  'clear': 'Clear',
  'apply': 'Apply',
  'reset': 'Reset',
  'optional': 'optional',
  'continueLabel': 'Continue',
  'share': 'Share',
  'copy': 'Copy',
  'copied': 'Copied',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'yesterday': 'Yesterday',
  'from': 'From',
  'to': 'To',
  'currency': 'AZN',
  'perSeat': 'per seat',
  'rating': 'Rating',
  'noResultsTitle': 'No results',
  'noResultsBody': 'Adjust your search and try again.',
  'emptyTitle': 'Nothing here yet',
  'refresh': 'Refresh',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'anonymous': 'Anonymous',
  'you': 'You',
  'now': 'now',
  'unknown': 'Unknown',

  // ------------------------------------------------------------ onboarding
  'onboard1Title': 'Find your travel companion',
  'onboard1Body':
      'Baku to Ganja, Sheki to Lankaran — we connect drivers and passengers heading the same way.',
  'onboard2Title': 'Split the cost',
  'onboard2Body':
      'Publish your empty seats and share the fuel bill. For passengers, a fraction of the taxi fare.',
  'onboard3Title': 'Safe and transparent',
  'onboard3Body':
      'Driver documents are reviewed, and every trip ends with a mutual rating. Phone numbers unlock only after a booking is confirmed.',
  'getStarted': 'Get started',

  // ------------------------------------------------------------------ auth
  'loginTitle': 'Welcome',
  'loginSubtitle':
      'Enter your number and we will text you a verification code.',
  'phoneNumber': 'Phone number',
  'phoneHint': '50 123 45 67',
  'sendCode': 'Send code',
  'termsPrefix': 'By continuing you agree to the ',
  'termsOfUse': 'Terms of Use',
  'termsAnd': ' and ',
  'privacyPolicy': 'Privacy Policy',
  'termsSuffix': '.',
  'otpTitle': 'Enter the code',
  'changeNumber': 'Change number',
  'resendCode': 'Resend code',
  'resendIn': 'Resend',
  'verify': 'Verify',
  'otpAutoHint': 'The code will be read automatically',
  'signingIn': 'Signing in…',

  // ------------------------------------------------------------------ role
  'roleTitle': 'How will you use the app?',
  'roleSubtitle': 'You can switch at any time.',
  'driver': 'Driver',
  'passenger': 'Passenger',
  'driverRoleDesc': 'I publish routes and share my empty seats.',
  'passengerRoleDesc': 'I look for trips and book a seat.',
  'driverMode': 'Driver mode',
  'passengerMode': 'Passenger mode',
  'activeMode': 'Mode',

  // --------------------------------------------------------------- profile
  'profile': 'Profile',
  'profileSetupTitle': 'Introduce yourself',
  'profileSetupSubtitle':
      'A name and a photo build trust with your travel companions.',
  'fullName': 'Full name',
  'fullNameHint': 'e.g. Rashad Aliyev',
  'about': 'About',
  'aboutHint': 'A few words about yourself…',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'genderUnspecified': 'Prefer not to say',
  'photo': 'Photo',
  'addPhoto': 'Add photo',
  'changePhoto': 'Change photo',
  'removePhoto': 'Remove photo',
  'takePhoto': 'Take a photo',
  'pickFromGallery': 'Choose from gallery',
  'editProfile': 'Edit profile',
  'memberSince': 'Member since',
  'completedTrips': 'Completed trips',
  'profileSaved': 'Profile updated',
  'verifiedBadge': 'Verified',
  'phoneVerified': 'Phone verified',

  // --------------------------------------------------------------- vehicle
  'vehicle': 'Vehicle',
  'vehicleInfo': 'Vehicle details',
  'vehicleBrand': 'Make',
  'vehicleBrandHint': 'e.g. Mercedes-Benz',
  'vehicleModel': 'Model',
  'vehicleModelHint': 'e.g. E 200',
  'vehicleColor': 'Colour',
  'vehiclePlate': 'Licence plate',
  'vehiclePlateHint': '10-AA-123',
  'vehicleYear': 'Year',
  'vehicleSeats': 'Passenger seats',
  'saveVehicle': 'Save vehicle',
  'vehicleSaved': 'Vehicle details saved',
  'noVehicle': 'No vehicle added',

  // ------------------------------------------------------------- documents
  'documents': 'Documents',
  'documentsTitle': 'Driver documents',
  'documentsSubtitle':
      'Your documents must be reviewed before you can publish rides. This usually takes up to 24 hours.',
  'docIdCard': 'ID card',
  'docDriverLicense': 'Driving licence',
  'docVehicleRegistration': 'Vehicle registration certificate',
  'docInsurance': 'Compulsory insurance',
  'docIdCardDesc': 'Both sides must be clearly readable.',
  'docDriverLicenseDesc': 'Must not be expired.',
  'docVehicleRegistrationDesc': 'Registration certificate of the vehicle.',
  'docInsuranceDesc': 'Compulsory insurance certificate.',
  'uploadDocument': 'Upload document',
  'replaceDocument': 'Replace document',
  'docStatusNotUploaded': 'Not uploaded',
  'docStatusPending': 'Under review',
  'docStatusApproved': 'Approved',
  'docStatusRejected': 'Rejected',
  'verificationPending': 'Your documents are under review',
  'verificationPendingBody':
      'You cannot publish rides until the review is complete.',
  'verificationApproved': 'Your driver status is approved',
  'verificationRejected': 'Documents rejected',
  'verificationRejectedBody':
      'Read the reason and upload your documents again.',
  'rejectionReason': 'Reason for rejection',
  'submitForReview': 'Submit for review',
  'documentsSubmitted': 'Documents submitted for review',
  'allDocumentsRequired': 'Please upload every document',

  // ------------------------------------------------------------------ ride
  'publishRide': 'Publish a ride',
  'publishRideShort': 'Publish',
  'editRide': 'Edit ride',
  'routeStep': 'Route',
  'scheduleStep': 'Date & time',
  'detailsStep': 'Terms',
  'fromCity': 'From',
  'toCity': 'To',
  'selectCity': 'Select a city',
  'searchCity': 'Search city',
  'swapCities': 'Swap',
  'date': 'Date',
  'time': 'Time',
  'selectDate': 'Select a date',
  'selectTime': 'Select a time',
  'seatsAvailable': 'Seats available',
  'pricePerSeat': 'Price per seat',
  'priceHint': 'e.g. 15',
  'rideNote': 'Additional note',
  'rideNoteHint': 'Meeting point, luggage rules, smoking, etc.',
  'pickupPoint': 'Pick-up point',
  'pickupPointHint': 'e.g. 20 Yanvar metro station',
  'dropoffPoint': 'Drop-off point',
  'publish': 'Publish ride',
  'ridePublished': 'Your ride is live',
  'rideUpdated': 'Ride updated',
  'rideDeleted': 'Ride deleted',
  'deleteRideConfirm': 'Delete this ride?',
  'deleteRideWithBookings':
      'This ride has confirmed bookings. Contact your passengers instead of deleting it.',
  'myRides': 'My rides',
  'activeRides': 'Active',
  'pastRides': 'Past',
  'rideActive': 'Active',
  'rideInactive': 'Inactive',
  'rideCompleted': 'Completed',
  'rideCancelled': 'Cancelled',
  'activateRide': 'Activate',
  'deactivateRide': 'Deactivate',
  'rideDetails': 'Ride details',
  'noRidesYet': 'No rides yet',
  'noRidesYetBody': 'Publish your first route and share your empty seats.',
  'rideFull': 'Fully booked',
  'departure': 'Departure',
  'instantBooking': 'Instant booking',
  'instantBookingDesc': 'Bookings are confirmed automatically',
  'requestBooking': 'Booking on request',
  'requestBookingDesc': 'You approve every booking yourself',

  // ---------------------------------------------------------------- search
  'searchTitle': 'Where are you going?',
  'searchRides': 'Find a ride',
  'anyDate': 'Any date',
  'passengersCount': 'Passengers',
  'searchResults': 'Search results',
  'filters': 'Filters',
  'sortBy': 'Sort by',
  'sortEarliest': 'Earliest',
  'sortCheapest': 'Cheapest',
  'sortTopRated': 'Top rated',
  'priceRange': 'Price range',
  'timeOfDay': 'Time of day',
  'morning': 'Morning',
  'afternoon': 'Afternoon',
  'evening': 'Evening',
  'night': 'Night',
  'onlyVerified': 'Verified drivers only',
  'noRidesFound': 'No rides on this route',
  'noRidesFoundBody': 'Try another date or set up an alert.',
  'recentSearches': 'Recent searches',
  'popularRoutes': 'Popular routes',
  'allActiveRides': 'All active rides',
  'noActiveRides': 'No active rides right now',
  'noActiveRidesBody': 'New listings show up here straight away.',

  // --------------------------------------------------------------- booking
  'bookSeat': 'Book a seat',
  'bookingTitle': 'Booking',
  'howManySeats': 'How many seats do you need?',
  'totalPrice': 'Total',
  'messageToDriver': 'Message to the driver',
  'messageToDriverHint': 'Hi, where should we meet?',
  'sendRequest': 'Send request',
  'bookNow': 'Book now',
  'bookingSent': 'Booking request sent',
  'bookingConfirmedToast': 'Booking confirmed',
  'myBookings': 'My bookings',
  'bookingRequests': 'Booking requests',
  'upcoming': 'Upcoming',
  'history': 'History',
  'statusPending': 'Pending',
  'statusConfirmed': 'Confirmed',
  'statusRejected': 'Declined',
  'statusCancelledByPassenger': 'Cancelled by passenger',
  'statusCancelledByDriver': 'Cancelled by driver',
  'statusCompleted': 'Completed',
  'cancelBooking': 'Cancel booking',
  'cancelBookingConfirm': 'Cancel this booking?',
  'bookingCancelled': 'Booking cancelled',
  'keepBooking': 'Keep booking',
  'cancelReleasesSeat':
      'Your seat is freed straight away. You can book again if you change your mind, but by then the seat may be gone.',
  'rebookSameRide': 'Book again',
  'rebookSameRideBody':
      'You cancelled this ride. If a seat is still free, you can book it again.',
  'rideClosedToYou': 'This ride is closed to you',
  'rideClosedToYouBody':
      'The driver has made their decision, so this ride cannot be applied to again. You can look at other rides on the same route.',
  'seatTakenAlready': 'The seat has gone',
  'seatTakenAlreadyBody':
      'Someone else took the seat after you cancelled. You can look at other rides on the same route.',
  'blockPassenger': 'Close the ride to this passenger',
  'blockPassengerConfirm':
      'This passenger will not be able to book this ride again. You can reopen it whenever you like.',
  'passengerBlocked': 'Ride closed to this passenger',
  'passengerBlockedBody':
      'After the cancellation you closed this ride to them — they cannot book it again.',
  'unblockPassenger': 'Reopen',
  'passengerBlockedMsg': 'The ride is now closed to this passenger',
  'passengerUnblockedMsg': 'The ride is open to this passenger again',
  'lateCancellationWarning':
      'Departure is close — cancelling now leaves the other side stranded.',
  'cancelReasonQuestion': 'Why are you cancelling?',
  'cancelReasonPlanChanged': 'My plans changed',
  'cancelReasonFoundCheaper': 'I found a cheaper ride',
  'cancelReasonNoAnswer': 'The driver is not responding',
  'cancelReasonVehicleProblem': 'Something came up with the car',
  'cancelReasonRescheduled': 'I changed the departure time',
  'cancelReasonOther': 'Another reason',
  'cancelReasonHint': 'Add a short note (optional)',
  'cancellationReasonTitle': 'Cancellation reason',
  'findAnotherRide': 'Find another ride',
  'findAnotherRideBody':
      'This ride cannot be applied to again, but you can browse the cheapest rides on the same route.',
  'confirmBooking': 'Confirm',
  'rejectBooking': 'Decline',
  'bookingConfirmedMsg': 'Booking confirmed, the passenger has been notified.',
  'bookingRejectedMsg': 'Booking declined.',
  'noBookingsYet': 'No bookings yet',
  'noBookingsYetBody': 'Find a ride and book your first seat.',
  'noRequestsYet': 'No requests yet',
  'noRequestsYetBody': 'Requests for your rides will show up here.',
  'seatsBooked': 'Seats booked',
  'bookedBy': 'Booked by',
  'markCompleted': 'Complete trip',
  'tripCompleted': 'Trip completed',

  // --------------------------------------------------------------- contact
  'contact': 'Contact',
  'callDriver': 'Call the driver',
  'callPassenger': 'Call the passenger',
  'sendMessage': 'Send a message',
  'phoneHiddenTitle': 'Number is hidden',
  'phoneHiddenBody':
      'For safety, phone numbers unlock only after the booking is confirmed.',
  'openWhatsapp': 'Message on WhatsApp',
  'cannotCall': 'Could not start the call',

  // ------------------------------------------------------------------ chat
  'chat': 'Chat',
  'messages': 'Messages',
  'typeMessage': 'Type a message…',
  'noMessages': 'No messages yet',
  'noMessagesBody': 'Sort out the trip details here.',
  'noConversations': 'No conversations',
  'noConversationsBody': 'A chat opens once a booking is confirmed.',
  'chatLockedTitle': 'Chat is locked',
  'chatLockedBody': 'You can write once the booking is confirmed.',

  // --------------------------------------------------------- notifications
  'notifications': 'Notifications',
  'markAllRead': 'Mark all as read',
  'noNotifications': 'No notifications',
  'noNotificationsBody': 'Booking and trip updates will appear here.',
  'notifNewBookingTitle': 'New booking request',
  'notifBookingConfirmedTitle': 'Your booking is confirmed',
  'notifBookingRejectedTitle': 'Your booking was declined',
  'notifBookingCancelledTitle': 'Booking cancelled',
  'notifRideReminderTitle': 'Trip reminder',
  'notifRideCancelledTitle': 'Ride cancelled',
  'notifNewMessageTitle': 'New message',
  'notifReviewRequestTitle': 'Rate your trip',
  'notifDocsApprovedTitle': 'Your documents are approved',
  'notifDocsRejectedTitle': 'Your documents were rejected',
  'notifAdminMessageTitle': 'Service notice',
  'notifAdminMarketingTitle': 'Promotion',
  'notifUnknownTitle': 'New notification',

  // Android notification channels — these names appear in system settings.
  'channelMessages': 'Messages',
  'channelMessagesDesc': 'New messages in your chats',
  'channelBookings': 'Bookings',
  'channelBookingsDesc': 'Booking requests, confirmations and cancellations',
  'channelReminders': 'Trip reminders',
  'channelRemindersDesc': 'A reminder before departure',
  'channelMarketing': 'Offers',
  'channelMarketingDesc': 'Promotions and news',
  'channelGeneral': 'General',
  'channelGeneralDesc': 'Account notices and everything else',

  // --------------------------------------------------------------- reviews
  'reviews': 'Reviews',
  'rateTrip': 'Rate the trip',
  'rateTripSubtitle': 'Your review helps other members.',
  'yourRating': 'Your rating',
  'writeComment': 'Write a review',
  'writeCommentHint': 'How was the trip?',
  'submitReview': 'Submit review',
  'reviewSubmitted': 'Thank you for your review',
  'noReviews': 'No reviews yet',
  'noReviewsBody': 'Be the first to write one.',
  'ratingPoor': 'Poor',
  'ratingFair': 'Fair',
  'ratingGood': 'Good',
  'ratingVeryGood': 'Very good',
  'ratingExcellent': 'Excellent',
  'reviewsAsDriver': 'As a driver',
  'reviewsAsPassenger': 'As a passenger',
  'pendingReviews': 'Trips awaiting your rating',

  // -------------------------------------------------------------- settings
  'settings': 'Settings',
  'language': 'Language',
  'languageAz': 'Azərbaycan',
  'languageRu': 'Русский',
  'languageEn': 'English',
  'appearance': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'notificationSettings': 'Notification settings',
  'pushNotifications': 'Push notifications',
  'bookingNotifications': 'Booking notifications',
  'messageNotifications': 'Message notifications',
  'reminderNotifications': 'Trip reminders',
  'marketingNotifications': 'Offers and news',
  'account': 'Account',
  'logout': 'Log out',
  'logoutConfirm': 'Log out of your account?',
  'deleteAccount': 'Delete account',
  'deleteAccountTitle': 'Delete account',
  'deleteAccountWarning':
      'Your account, rides and booking history will be permanently deleted. This cannot be undone.',
  'deleteAccountConfirmHint': 'Type DELETE to confirm',
  'deleteAccountKeyword': 'DELETE',
  'accountDeleted': 'Account deleted',
  'support': 'Support',
  'helpCenter': 'Help centre',
  'contactSupport': 'Contact us',
  'rateApp': 'Rate the app',
  'aboutApp': 'About',
  'version': 'Version',
  'legal': 'Legal',

  // ----------------------------------------------------------------- admin
  'adminPanel': 'Admin panel',
  'adminOverview': 'Overview',
  'adminDocuments': 'Document review',
  'adminUsers': 'Users',
  'adminRides': 'Rides',
  'adminReports': 'Reports',
  'adminNoPending': 'No documents awaiting review',
  'approve': 'Approve',
  'block': 'Block',
  'unblock': 'Unblock',
  'blocked': 'Blocked',
  'userBlocked': 'User blocked',
  'userUnblocked': 'User unblocked',
  'totalUsers': 'Users',
  'totalDrivers': 'Drivers',
  'totalRides': 'Rides',
  'totalBookings': 'Bookings',
  'pendingVerifications': 'Pending reviews',
  'openReports': 'Open reports',
  'reportUser': 'Report',
  'reportReason': 'Reason',
  'reportSubmitted': 'Your report has been submitted',
  'resolveReport': 'Resolve',
  'adminOnly': 'This section is for administrators only',

  // ------------------------------------------------------------ validation
  'fieldRequired': 'This field is required',
  'invalidPhone': 'That number is not valid',
  'invalidName': 'Name must be at least 3 letters',
  'invalidOtpFormat': 'The code must be 6 digits',
  'invalidPlate': 'Plate format: 10-AA-123',
  'invalidPrice': 'Price must be between 1 and 500 AZN',
  'invalidYear': 'That year is not valid',
  'sameCityError': 'Origin and destination cannot be the same',
  'pastDateError': 'You cannot pick a past date',
  'tooFarDateError': 'Rides can be published up to 3 months ahead',
  'selectAtLeastOneSeat': 'Select at least one seat',
  'commentTooLong': 'Your review is too long',

  // ---------------------------------------------------------------- errors
  'errNetwork': 'No internet connection',
  'errTimeout': 'The operation took too long',
  'errServer': 'Something failed on the server',
  'errUnauthenticated': 'Your session expired, please sign in again',
  'errPermissionDenied': 'You do not have permission for this action',
  'errNotFound': 'Not found',
  'errAlreadyExists': 'This already exists',
  'errInvalidInput': 'The information you entered is not valid',
  'errInvalidPhoneNumber': 'That phone number is not valid',
  'errInvalidOtp': 'Wrong code',
  'errOtpExpired': 'The code expired, request a new one',
  'errTooManyRequests': 'Too many attempts, try again later',
  'errSeatsUnavailable': 'Not enough seats available',
  'errRideNotBookable': 'This ride is no longer open for booking',
  'errBookingNotCancellable': 'This booking cannot be cancelled',
  'errSelfBooking': 'You cannot book your own ride',
  'errDocumentsPending': 'Your documents are still under review',
  'errDocumentsRejected': 'Your documents must be approved before publishing',
  'errStorage': 'The file could not be uploaded',
  'errCancelled': 'The operation was cancelled',
  'errUnknown': 'An unexpected error occurred',
  'errorTitle': 'Something went wrong',

  // ------------------------------------------------------------ navigation
  'navSearch': 'Search',
  'navRides': 'Rides',
  'navBookings': 'Bookings',
  'navChat': 'Chat',
  'navProfile': 'Profile',
  'navPublish': 'Publish',
  'navRequests': 'Requests',

  // ------------------------------------------------- API-specific
  'filtersLocalNote':
      'Price and time filters apply only to the results already loaded.',
  'alreadyRequestedTitle': 'You have already applied',
  'alreadyRequestedBody':
      'You either already have a booking on this ride, or the driver has made their decision. You can look at other rides on the same route.',
  'alreadyReviewedBody': 'You have already reviewed this trip.',
  'conversationLocked':
      'This conversation is closed because the booking was cancelled.',
  'linkUnavailableTitle': 'No longer available',
  'linkUnavailableBody':
      'The ride or booking this notification refers to has been deleted.',
  'loadMore': 'Load more',
  'documentsNoPreview': 'Uploaded documents are not shown, for security.',
  'seatsIncludeDriver': 'Total seats, including the driver',
  'plateVisibleToYou': 'The plate is visible only to you',
  'routeNotEditable':
      'The route and vehicle cannot be changed after publishing.',
  'cancelRide': 'Cancel ride',
  'cancelRideConfirm':
      'This ride will be cancelled, and every pending and confirmed booking with it. The passengers will be notified.',
  'dropoffPointHint': 'e.g. Gabala centre',
  'city': 'City',
  'birthYear': 'Year of birth',
  'docBackSideRequired':
      'This document needs both sides — the upload was cancelled.',
  'docBothSides': 'Pick the front side first, then the back.',
  'devCodeTitle': 'SMS is not wired up yet',
  'devCodeBody':
      'The server returns the code in its reply. Tap it to fill the boxes.',
  'chooseModeTitle': 'How do you want to continue?',
  'chooseModeBody':
      'You stay on the side you pick here. Sign out and back in to change it.',
  'driverModeNeedsVehicle':
      'Driver mode needs a car. Without one the app opens in passenger mode and moves you across the moment you add one under Profile → Vehicle.',
};
